#!/bin/sh

sudo yum install python27 python27-devel
echo "change python version to 2.7"
pause
sudo rm -f /usr/bin/python
sudo ln -s /usr/bin/python27 /usr/bin/python
echo "* MANUAL change yum python version"
pause
sudo vi /usr/bin/yum
echo "install pip"
pause
wget https://pypi.python.org/packages/source/p/pip/pip-1.3.1.tar.gz
tar zxvf pip-1.3.1.tar.gz
cd pip-1.3.1
sudo python setup.py install
echo "install virtualenv"
pause
sudo pip install virtualenv

